version: "3.9"

services:
  postgres:
    container_name: postgres-db
    image: postgres:13
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  # app:
  #   container_name: node-app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - POSTGRES_URL=${POSTGRES_URL}
  #     - PORT=${PORT}
  #     - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
  #     - JWT_SECRET=${JWT_SECRET}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   command: node dist/server.js # Chạy file build JS từ TypeScript
  #   volumes:
  #     - /app/node_modules # Giữ node_modules trong container để không bị ghi đè
  #     # - .:/app                 # Mở dòng này khi phát triển, mount toàn bộ code vào container

volumes:
  postgres-data:
