name: CI - Test Docker Compose

on:
  push:
    branches:
      - master
      - Stogare-jwt-and-google-sigin-signout
      - add-redis-matching
  pull_request:
    branches: [master]

jobs:
  test-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install docker-compose -y

      - name: Run Docker Compose
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          PORT: ${{ secrets.PORT }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: docker-compose up -d --build

      - name: Wait for app to be healthy
        run: |
          sleep 10
          docker logs node-app
